services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: soul_frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:80"
    command: nginx -g 'daemon off;'

  db:
    image: postgres:18.6-alpine
    container_name: soul_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soul_game_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: soul_backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: soul_game_dev
      MIX_ENV: dev
    volumes:
      - ./backend/soul_game:/app
      - /app/deps
      - /app/_build
    ports:
      - "4000:4000"

volumes:
  pgdata:
